#!/bin/bash

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
	i3-nagbar -m 'Battery low!' -b 'Hibernate!' 'i3lock -c 000000 -i /home/skropf/.wallpaper.png && systemctl hibernate' >/dev/null 2>&1 &
fi
