#!/bin/bash
#
# script for managing vpn services
#


if [[ "_$1" == "_" ]]
then
	echo "Usage: $0 <endpoint> <internal|external> <on|off>"
	echo "Usage: $0 uni <user|kill|info> <all(only with user)> (for university use)"
	echo "Usage: $0 status ... shows current connection"
fi

if [[ "_$1" == "_uni" ]]
then
	if [[ _$2 =~ _[a-z] ]]
	then
		if [ _$3 == '_all' ]
		then
			f5fpc -s -t vpn.univie.ac.at:8443 -u $1
		elif [ _$2 == '_kill' ]
		then
			f5fpc -o
		elif [ _$2 == '_info' ]
		then
			f5fpc --info
		else
			f5fpc -s -t vpn.univie.ac.at -u $1
		fi
	fi
	
else
	if [[ "_$3" == "_on" ]]
	then
		sudo systemctl start wg-quick@$1-$2;
	elif [[ "_$3" == "_off" ]]
	then
		sudo systemctl stop wg-quick@$1-$2;
	else
		echo "Usage: $0 <endpoint> <internal|external> <on|off>";
	fi
fi
